app_conf_path = r"D:\PythonWorkSpace\Test_Api_App\config\app.ini"
ele_class_name_conf_path = "D:\PythonWorkSpace\Test_Api_App\config\ele_class_name.ini"
ele_id_conf_path = "D:\PythonWorkSpace\Test_Api_App\config\ele_id.ini"
ele_location_conf_path = "D:\PythonWorkSpace\Test_Api_App\config\ele_id.ini"
ele_xpath_conf_path = "D:\PythonWorkSpace\Test_Api_App\config\ele_xpath.ini"
parameter_conf_path = "D:\PythonWorkSpace\Test_Api_App\config\parameter.ini"